env:
  es6: true
  jest: true
  node: true
parserOptions:
  ecmaVersion: 2019
  sourceType: 'module'
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
rules:
  prettier/prettier: 'error'
