semi: false
singleQuote: true
jsxSingleQuote: true
tabWidth: 4
endOfLine: lf
useTabs: false
printWidth: 100
trailingComma: all
overrides:
  - files: '*.y?ml'
    options:
      tabWidth: 2
      useTabs: false
