#!/usr/bin/env bash
source "$SCRIPTS_PATH/common.sh"

mkdir -p "$WORKSPACE_MOUNT_PATH"
assert $? "Failed to create mount path" || exit $?

[ -n "$USERNAME" ]
assert $? "Failed to create user. Username not defined" || exit $?

log:sep "Creating user $USERNAME"

useradd -ms /bin/bash -g developers $USERNAME -p "$PASSWORD" &&
    adduser $USERNAME sudo &&
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >"/etc/sudoers.d/$USERNAME" &&
    chmod 0440 /etc/sudoers.d/$USERNAME
assert $? "Failed to create user" || exit $?

sudo -E -H -u "$USERNAME" "${SCRIPTS_PATH}/image/prepare_user"
assert $? "Failed to prepare user" || exit $?
