#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../scripts/common.sh"

args=()
while [ $# -gt 0 ]; do
    case $1 in
    -h | --help)
        log:help "
Run farfeched as a docker container

FLAGS:
    --build | -b    Build before running
"
        exit 0
        ;;
    --build | -b)
        export BUILD=1
        ;;
    *)
        # Catch positional arguments.
        args+=("$1")
        ;;
    esac
    shift
done

if [ $BUILD -eq 1 ]; then
    "$REPO_PATH/docker/build" || exit
fi

log:sep "Starting farfetched service."
docker run -p 0.0.0.0:9000:9000 -p 0.0.0.0:9001:9001 -p 0.0.0.0:9022:22 \
    -v "$REPO_PATH/.local/bound:/workspace" \
    -v "$HOME/.ssh:/mnt/homelinked_volumes/.ssh" \
    -it --rm farfetched:debug "${args[@]}"
