#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../scripts/common.sh"

BUILD=1
USERNAME="$(whoami)"
args=()
while [ $# -gt 0 ]; do
    case $1 in
    -h | --help)
        log:help "
Run farfeched as a docker container

ARGS:
    --user          The dev username (requires build if changed)
    --presist       A list of folders to presist.
FLAGS:
    --help | -h     Show this help menu
    --no-build      Do not build.
"
        exit 0
        ;;
    --no-build)
        BUILD=0
        ;;
    --user)
        shift
        USERNAME="$1"
        ;;
    --presist)
        shift
        PRESIST_FOLDERS="$1"
        ;;
    -*)
        assert 2 "Unknown option $1" || exit $?
        ;;
    *)
        # Catch positional arguments.
        assert 2 "Unknown input $1" || exit $?
        ;;
    esac
    shift
done

: "${IMAGE_NAME="farfetched"}"
: "${IMAGE_TAG="debug"}"

log "Initializing farfetched run for $USERNAME"

export IMAGE_NAME
export IMAGE_TAG

if [ $BUILD -eq 1 ]; then
    "$REPO_PATH/docker/build" "${args[@]}" --build-arg USER="$USERNAME" --build-arg PRESIST_FOLDERS="$PRESIST_FOLDERS" || exit $?
fi

log:sep "Starting farfetched service."
docker run -p 0.0.0.0:9000:9000 -p 0.0.0.0:9001:9001 -p 0.0.0.0:9022:22 \
    -v "$REPO_PATH/.local/bound:/workspace" \
    -it --rm ${IMAGE_NAME}:${IMAGE_TAG}
