#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

: ${REPO_PATH="$(realpath "$SCRIPTS_PATH/../")"}
: ${ARCHIVE_PATH="/tmp/helm.tar.gz"}
: ${HELM_SOURCE_PATH="$REPO_PATH/helm"}
# go to the repo path
cd "$SCRIPTS_PATH/../"

log:sep "Creating helm release @ $HELM_SOURCE_PATH -> $ARCHIVE_PATH"
tar -czvf "$ARCHIVE_PATH" -C "$HELM_SOURCE_PATH" .
assert $? "Failed to create helm archive" || exit $?
log:info "Done"