#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

: "${WORKSPACE_MOUNT_PATH:="/workspace"}"
: "${INITIALIZED_STAMP_FILE_NAME:="initialized.stamp"}"
: "${BOUND_FOLDERS:="$HOME $PRESIST_FOLDERS"}"

BOUND_FOLDERS="$(trim "$BOUND_FOLDERS")"

function get_stamp_file_name() {
    local fname="$INITIALIZED_STAMP_FILE_NAME"
    : "${fname:="initialized.stamp"}"
    echo "$1/$fname"
}

function as_mounted_folder() {
    local folder="$(basename "$1")"
    echo "$WORKSPACE_MOUNT_PATH/$folder"
}

function link_to_workspace() {
    for folder in "$@"; do
        folder="$(trim "$folder")"
        if [ -z "$folder" ]; then
            continue
        fi
        if [ -d "$folder" ] || [ -f "$folder" ]; then
            sudo rm -R "$folder"
            assert $? "Failed to remove $folder" || return $?
        fi

        local mounted_folder="$(as_mounted_folder "$folder")"

        log "Linking $mounted_folder -> $folder"
        sudo ln -sf "$mounted_folder" "$folder"
        assert $? "Failed to link workspace folder" || return $?
    done
}

function move_to_workspace() {
    for folder in "$@"; do
        folder="$(trim "$folder")"
        if [ -z "$folder" ]; then
            continue
        fi

        local mounted_folder="$(as_mounted_folder "$folder")"

        # if was stamped then continue.
        if [ -d "$mounted_folder" ]; then
            log "Skipped moving $folder, exists."
            continue
        fi

        log "Copying $folder -> $mounted_folder"
        if [ -d "$folder" ] || [ -f "$folder" ]; then
            cp -a "$folder" "$WORKSPACE_MOUNT_PATH"
            assert $? "Failed to move $folder to $mounted_folder" || return $?
        else
            log:warning "Skipping $folder, not found"
        fi
    done
}

function process_moves() {
    move_to_workspace $BOUND_FOLDERS
    assert $? "Failed to initialzie binds" || return $?
}

function process_links() {
    link_to_workspace $BOUND_FOLDERS
    assert $? "Failed to link workspace" || exit $?
}

log:sep "Initializing mounts ($INITIALIZED_STAMP_FILE_NAME)..."

log "Validating user sudo access"
sudo echo "" &>/dev/null
assert $? "Failed to login as user"

STARTED_AT="$(realpath "$PWD")"
cd /
process_moves && process_links || exit $?
cd "$STARTED_AT"
assert $? "Failed to move back to original directory"
