#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

: "${WORKSPACE_MOUNT_PATH:="/workspace"}"
: "${WORKSPACE_STAMP_FILE:="$WORKSPACE_MOUNT_PATH/initialized.stamp"}"
: "${CONTAINER_STAMP_FILE:="/tmp/initialized.stamp"}"
: "${BOUND_FOLDERS:="/home/$DEV_USER $PRESIST_FOLDERS"}"

BOUND_FOLDERS="$(trim "$BOUND_FOLDERS")"

function link_to_workspace() {
    for folder in "$@"; do
        if [ -d "$folder" ] || [ -f "$folder" ]; then
            sudo rm -R "$folder"
            assert $? "Failed to remove $folder" || return $?
        fi
        sudo ln -sf "$WORKSPACE_MOUNT_PATH/$(basename "$folder")" "$folder"
        assert $? "Failed to link workspace folder" || return $?
    done
}

function move_to_workspace() {
    for folder in "$@"; do
        log "Binding $folder ..."
        if [ -d "$folder" ] || [ -f "$folder" ]; then
            sudo mv "$folder" "$WORKSPACE_MOUNT_PATH"
            assert $? "Failed to move $folder to workdir" || return $?
        else
            log:warning "Skipping $folder, not found"
        fi
    done
}

function process_moves() {
    if [ -f "$WORKSPACE_STAMP_FILE" ]; then
        return
    fi
    log:sep "Initializing mounts ($WORKSPACE_STAMP_FILE missing in mount)..."
    log "Validating user sudo access"
    sudo echo "" &>/dev/null
    assert $? "Failed to login as user"
    log "Binding locals to volume"
    move_to_workspace $BOUND_FOLDERS
    assert $? "Failed to initialzie binds" || return $?
    touch "$WORKSPACE_STAMP_FILE"
    assert $? "Failed to initialize workspace stamp"
}

function process_links() {
    if [ -f "$CONTAINER_STAMP_FILE" ]; then
        return
    fi
    log "Linking mounts.."
    sudo echo "" &>/dev/null
    link_to_workspace $BOUND_FOLDERS
    assert $? "Failed to link workspace" || exit $?
    touch "$CONTAINER_STAMP_FILE"
    assert $? "Failed to initialize container stamp"
}

STARTED_AT="$(realpath "$PWD")"
cd /
process_moves && process_links || exit $?
cd "$STARTED_AT"
assert $? "Failed to move back to original directory"
