#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

: "${WORKSPACE_MOUNT_PATH:="/workspace"}"
: "${INITIALIZED_STAMP_FILE_NAME:="initialized.stamp"}"
: "${BOUND_FOLDERS:="$HOME $PRESIST_FOLDERS"}"

BOUND_FOLDERS="$(trim "$BOUND_FOLDERS")"

function get_stamp_file_name() {
    local fname="$INITIALIZED_STAMP_FILE_NAME"
    : "${fname:="initialized.stamp"}"
    echo "$1/$fname"
}

function is_stamped() {
    local folder="$1"
    local stamp_file="$(get_stamp_file_name "$folder")"
    if [ -f "$stamp_file" ]; then
        return 1
    fi
    log "Stamping bind directory @ $stamp_file"
    echo "$(date)" >"$stamp_file"
    # assert $? "Failed to stamp bind directory @ $stamp_file" || exit $?
    return 0
}

function link_to_workspace() {
    for folder in "$@"; do
        folder="$(trim "$folder")"
        if [ -z "$folder" ]; then
            continue
        fi
        # if was stamped then continue.
        is_stamped "$folder" || continue

        if [ -d "$folder" ] || [ -f "$folder" ]; then
            sudo rm -R "$folder"
            assert $? "Failed to remove $folder" || return $?
        fi
        sudo ln -sf "$WORKSPACE_MOUNT_PATH/$(basename "$folder")" "$folder"
        assert $? "Failed to link workspace folder" || return $?
    done
}

function move_to_workspace() {
    for folder in "$@"; do
        folder="$(trim "$folder")"
        if [ -z "$folder" ]; then
            continue
        fi

        # if was stamped then continue.
        is_stamped "$folder" || continue

        log "Binding $folder ..."
        if [ -d "$folder" ] || [ -f "$folder" ]; then
            sudo mv "$folder" "$WORKSPACE_MOUNT_PATH"
            assert $? "Failed to move $folder to workdir" || return $?
        else
            log:warning "Skipping $folder, not found"
        fi
    done
}

function process_moves() {
    log:sep "Initializing mounts ($WORKSPACE_STAMP_FILE missing in mount)..."
    log "Validating user sudo access"
    sudo echo "" &>/dev/null
    assert $? "Failed to login as user"
    log "Binding locals to volume"
    move_to_workspace $BOUND_FOLDERS
    assert $? "Failed to initialzie binds" || return $?
}

function process_links() {
    log "Linking mounts.."
    sudo echo "" &>/dev/null
    link_to_workspace $BOUND_FOLDERS
    assert $? "Failed to link workspace" || exit $?
}

STARTED_AT="$(realpath "$PWD")"
cd /
process_moves && process_links || exit $?
cd "$STARTED_AT"
assert $? "Failed to move back to original directory"
