#!/usr/bin/env bash
source "$SCRIPTS_PATH/common.sh"
USERNAME="$1"
PASSWORD="$2"

mkdir -p "$WORKSPACE_MOUNT_PATH"
assert $? "Failed to create mount path" || exit $?

[ -n "$USERNAME" ]
assert $? "Failed to create user. Username not defined" || exit $?

log:sep "Creating user $USERNAME"

groupadd developers &&
    useradd -ms /bin/bash -g developers $USERNAME -p "$PASSWORD" &&
    adduser $USERNAME sudo &&
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >"/etc/sudoers.d/$USERNAME" &&
    chmod 0440 /etc/sudoers.d/$USERNAME
assert $? "Failed to create user"

log "Setting up vscode" &&
    mkdir -p $HOME/.config/Code/User &&
    mkdir -p $HOME/.local/share/code-server/User &&
    cp /defaults/vscode_default_settings.json $HOME/.config/Code/User &&
    cp /defaults/vscode_default_settings.json $HOME/.local/share/code-server/User
assert $? "Failed to create default vscode settings" || exit $?

su -c '"${SCRIPTS_PATH}/image/fix_folder_permissions" "/workspace"' "$USERNAME"
assert $? "Failed to adjust permissions" || exit $?

su -c '"${SCRIPTS_PATH}/image/install_vscode_server_user_extensions"' "$USERNAME"
assert $? "Failed to install vscode server extentions" || exit $?
