#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
log:sep "Installing vscode extentions"

ALL_EXTENTIONS="$(cat "$SCRIPTS_PATH/image/install_vscode_server_user_extensions.txt")"
ALL_EXTENTIONS="$(trim "$ALL_EXTENTIONS $VSCODE_EXTENSIONS")"

EXTENTSIONS_DIR_COMMAND=""
if [ "$(whoami)" == "root" ]; then
    log "Root user detected, installing extensions to global directory."
    EXTENTSIONS_DIR_COMMAND="--extensions-dir /usr/lib/code-server/lib/vscode/extensions"
else
    log "Installing vscode extensions for user: $(whoami)"
fi

if [ -n "$ALL_EXTENTIONS" ]; then
    ALL_EXTENTIONS=($ALL_EXTENTIONS)
    for ext in "${ALL_EXTENTIONS[@]}"; do
        code-server \
            $EXTENTSIONS_DIR_COMMAND \
            --install-extension "$ext"
    done
else
    log "No extensions found. Skipping."
fi
