#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

log:sep "Installing vscode http server"

log "Getting latest vscode-server version.."
VSCODE_SERVER_REPO="https://github.com/cdr/code-server"
VSCODE_SERVER_VERSION=$(get_github_latest_release_version "$VSCODE_SERVER_REPO" | grep -Eo "[^v].*$")
assert $? "Error resolving latest vscode-server version @ $VSCODE_SERVER_REPO" || exit $?

#https://github.com/cdr/code-server/releases/download/3.6.2/code-server-3.6.2-linux-amd64.tar.gz
#https://github.com/cdr/code-server/releases/download/v3.6.2/code-server-3.6.2-linux-amd64.tar.gz
#https://github.com/cdr/code-server/releases/download/v3.6.2/code-server-3.6.2-amd64.rpm
VSCODE_DOWNLOAD_URL="$VSCODE_SERVER_REPO/releases/download/v${VSCODE_SERVER_VERSION}/code-server-${VSCODE_SERVER_VERSION}-linux-amd64.tar.gz"

export VSCODE_SERVER_FOLDER="$APPS_DIR/vscode-server"

log "Downloading and installing vscode server from $VSCODE_DOWNLOAD_URL"
mkdir -p "$VSCODE_SERVER_FOLDER" &&
    curl -sL "$VSCODE_DOWNLOAD_URL" | tar -xzvf - -C "$VSCODE_SERVER_FOLDER" --strip 1 >>/tmp/code_server_install_log.log
assert $? "Failed to download and extract vscode server" || exit $?

COMMAND_FILE="$VSCODE_SERVER_FOLDER/bin/code-server"
log "Linking and setting permissions @ $COMMAND_FILE -> /usr/local/bin/code-server"
chmod +x "$COMMAND_FILE"
assert $? "Failed to set run permissions on $COMMAND_FILE" || exit $?
sudo ln -sf "$COMMAND_FILE" "/usr/local/bin/code-server" &&
    sudo ln -sf "$COMMAND_FILE" "/usr/local/bin/code"
assert $? "Failed to link binaries"

log "Upgrading extention search extension gallery"
python3 "$SCRIPTS_PATH/installs/install_vscode_server.py"
assert $? "Failed to upgrade vscode extension search gallery"
