#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

VSCODE_SERVER_FOLDER="/usr/lib/code-server/lib/vscode"
export VSCODE_SERVER_FOLDER
log:sep "Installing vscode http server @ $VSCODE_SERVER_FOLDER"
curl -fsSL https://code-server.dev/install.sh | sh

python3 "$SCRIPTS_PATH/installs/install_vscode_server.py"
assert $? "Failed to upgrade vscode extension search gallery" || exit $?
log "Upgraded search extension gallery"
